import { useEffect, useMemo, useState } from 'react'
import { Save24Regular, Send24Regular } from '@fluentui/react-icons'
import { Button, Card, Checkbox, Field, Select } from '@fluentui/react-components'
import { api, type Group, type ScheduleRecord, type TimelineRecord } from './api'
type Course = { id: string; name: string; color?: string }
type Entry = { id: string; type?: string; startTime: string; endTime: string; title?: string; subjectId?: string }
type Day = { id: string; entries: Entry[]; dayOfWeek?: number[]; weeks?: 'all' | number | number[] | null }
type Schedule = { meta: { id: string; version: 1; maxWeekCycle: number; startDate: string }; subjects: Course[]; days: Day[]; timelineIds?: string[] }
type Props = { organizationId: string; groups: Group[]; onComplete: (message: string, tone?: 'success' | 'error') => void }
const DAYS = ['周一', '周二', '周三', '周四', '周五', '周六', '周日']
function activeDay(schedule: Schedule, day: number, week: number) { return schedule.days.find((item) => item.dayOfWeek?.includes(day) && (item.weeks === 'all' || item.weeks == null || item.weeks === week || Array.isArray(item.weeks) && item.weeks.includes(week))) }
function emptySchedule(timeline: TimelineRecord): Schedule { return { meta: { id: crypto.randomUUID(), version: 1, maxWeekCycle: 2, startDate: new Date().toISOString().slice(0, 10) }, subjects: [], days: [{ ...(timeline.timeline as unknown as Day), id: timeline.id, entries: (timeline.timeline.entries as Entry[] ?? []).map((entry) => ({ ...entry, subjectId: undefined })) }] } }
export function CrossGroupScheduleWorkspace({ organizationId, groups, onComplete }: Props) {
  const [timelines, setTimelines] = useState<TimelineRecord[]>([]); const [records, setRecords] = useState<ScheduleRecord[]>([]); const [timelineId, setTimelineId] = useState(''); const [selectedGroups, setSelectedGroups] = useState<string[]>([]); const [day, setDay] = useState(1); const [week, setWeek] = useState(1); const [drafts, setDrafts] = useState<Record<string, Schedule>>({})
  useEffect(() => { if (!organizationId) return; void Promise.all([api.timelines(organizationId), api.schedules(organizationId)]).then(([nextTimelines, nextRecords]) => { setTimelines(nextTimelines); setRecords(nextRecords) }).catch(() => undefined) }, [organizationId])
  const selectedTimeline = timelines.find((item) => item.id === timelineId); const cycleWeeks = typeof selectedTimeline?.timeline.weeks === 'number' ? selectedTimeline.timeline.weeks : 1; const entries = useMemo(() => selectedTimeline ? (selectedTimeline.timeline.entries as Entry[] ?? []) : [], [selectedTimeline])
  function loadGroup(id: string) { if (drafts[id]) return; const record = records.find((item) => item.group_ids.includes(id)); const fallback = selectedTimeline ?? { id: crypto.randomUUID(), organization_id: organizationId, name: '空时间线', timeline: { entries: [] }, created_at: '', updated_at: '' }; setDrafts((value) => ({ ...value, [id]: record ? structuredClone(record.schedule) as unknown as Schedule : emptySchedule(fallback) })) }
  function toggleGroup(id: string) { setSelectedGroups((value) => value.includes(id) ? value.filter((item) => item !== id) : [...value, id]) }
  function setCell(groupId: string, entryId: string, subjectId: string) { const current = drafts[groupId]; if (!current) return; const target = activeDay(current, day, week) ?? current.days[0]; if (!target) return; setDrafts((value) => ({ ...value, [groupId]: { ...current, days: current.days.map((item) => item.id === target.id ? { ...item, entries: item.entries.map((entry) => entry.id === entryId ? { ...entry, subjectId } : entry) } : item) } })) }
  async function save(publish: boolean) { try { if (!selectedTimeline || !selectedGroups.length) return; for (const groupId of selectedGroups) { const draft = drafts[groupId]; if (!draft) continue; const payload = { ...draft, timelineIds: [selectedTimeline.id] }; const current = records.find((item) => item.group_ids.includes(groupId)); const result = current ? await api.updateSchedule(current.id, { name: current.name, schedule: payload }) : await api.publishSchedule({ organization_id: organizationId, name: groups.find((item) => item.id === groupId)?.name ?? '按天排课', schedule: payload, group_ids: [] }); if (publish) await api.assignSchedule(result.id, [groupId]) } onComplete(publish ? '已按分组保存并发布' : '已保存按天排课草稿') } catch (error) { onComplete(error instanceof Error ? error.message : '保存按天排课失败', 'error') } }
  return <div className="cross-group-workspace"><Card className="cross-group-panel"><div className="section-heading"><div><h2>按天拉通排课</h2><span>共用一条时间线，按天为多个分组同时安排课程。</span></div><div className="form-actions"><Button appearance="secondary" icon={<Save24Regular />} onClick={() => void save(false)}>保存草稿</Button><Button appearance="primary" icon={<Send24Regular />} onClick={() => void save(true)}>保存并发布</Button></div></div><div className="cross-group-toolbar"><Field label="公共时间线"><Select value={timelineId} onChange={(event) => { setTimelineId(event.target.value); setDrafts({}) }}><option value="">选择时间线</option>{timelines.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><div className="group-picker"><span className="group-picker-label">参与分组</span><div className="checks fluent-checks">{groups.map((group) => <Checkbox id={`cross-group-${group.id}`} key={group.id} checked={selectedGroups.includes(group.id)} onChange={(_, data) => { toggleGroup(group.id); if (data.checked) loadGroup(group.id) }} label={group.name} />)}</div></div></div><div className="day-pills fluent-day-pills">{DAYS.map((label, index) => <Button appearance={day === index + 1 ? 'primary' : 'secondary'} key={label} onClick={() => setDay(index + 1)}>{label}</Button>)}</div><div className="week-toolbar"><Button appearance="subtle" disabled={week <= 1} onClick={() => setWeek(week - 1)}>上一周</Button><strong>循环第 {week} 周</strong><Button appearance="subtle" disabled={!selectedTimeline || week >= cycleWeeks} onClick={() => setWeek(week + 1)}>下一周</Button></div><div className="cross-group-grid" style={{ gridTemplateColumns: `minmax(180px, 1fr) repeat(${selectedGroups.length || 1}, minmax(180px, 1fr))` }}><div className="grid-head">时间段</div>{selectedGroups.map((groupId) => <div className="grid-head" key={groupId}>{groups.find((item) => item.id === groupId)?.name ?? '未命名分组'}</div>)}{entries.map((entry, index) => <div className="cross-group-row" key={entry.id}><div className="time-cell"><strong>第 {index + 1} 节</strong><span>{entry.startTime}–{entry.endTime}</span></div>{selectedGroups.map((groupId) => { const draft = drafts[groupId]; const current = draft ? activeDay(draft, day, week) ?? draft.days[0] : undefined; const value = current?.entries.find((item) => item.id === entry.id)?.subjectId ?? ''; return <Select key={groupId} aria-label={`${groups.find((item) => item.id === groupId)?.name ?? '分组'} 第 ${index + 1} 节`} value={value} onChange={(event) => setCell(groupId, entry.id, event.target.value)}><option value="">未设置</option>{draft?.subjects.map((course) => <option key={course.id} value={course.id}>{course.name}</option>)}</Select> })}</div>)}</div></Card></div>
}
